version: "1.0"
stages:
  - "clone"
  - "build"
  - test
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "romaninsh/terms"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  cecil:
    title: Cecil Build Site
    type: freestyle
    stage: build
    working_directory: "${{clone}}"
    arguments:
      image: php
      entry_point: /bin/sh
      commands:
        - curl -LO https://cecil.app/cecil.phar
        - php cecil.phar build

  build:
    title: "Building Docker image"
    stage: "build"
    type: "build"
    registry: saasty
    dockerfile: Dockerfile
    working_directory: "${{clone}}"
    tag: '${{CF_REVISION}}'
    image_name: saasty/nearly.guru

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: byrnedo/alpine-curl
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - curl http://app:8080/
    stage: "test"
    services:
      composition:
        app:
          image: '${{build}}'
          ports:
           - 8080
      readiness:
        timeoutSeconds: 30
        periodSeconds: 15
        image: byrnedo/alpine-curl
        commands:
          - "curl http://app:8080/"


